source: /example1/
collections_config:
  content_posts:
    path: content/posts
    name: Content Posts
    icon: content_paste
paths:
  static: static
  uploads: static/uploads
timezone: Europe/Athens
markdown:
  engine: commonmark
  options:
    gfm: true
    linkify: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    breaks: false
    xhtml: false
    attributes: false
    typographer: false
    treat_indentation_as_code: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
