_schema: _schema
source: /
paths:
  uploads: static/uploads
  static: static
collections_config:
  content_posts:
    path: content/posts
    name: Content Posts
    icon: content_paste
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: content/home
    glob: []
    name:
    singular_name:
    icon: notes
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description: ''
    preview:
    sort:
    sort_options:
    _editables:
    _enabled_editors:
      - visual
      - content
      - data
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
_enabled_editors:
  - visual
  - content
  - data
_editables:
  text:
    allow_custom_markup: true
    remove_custom_markup: false
    bold: true
    copyformatting:
    italic:
    link:
    paths:
    redo:
    removeformat:
    strike:
    subscript:
    superscript:
    underline:
    undo:
  content:
    allow_custom_markup: false
    remove_custom_markup: false
    blockquote:
    bold:
    bulletedlist:
    center:
    code:
    copyformatting:
    embed:
    expandable:
    format:
    height:
    horizontalrule:
    image:
    image_size_attributes: true
    indent:
    italic:
    justify:
    left:
    link:
    mime_type:
    numberedlist:
    outdent:
    paths:
    redo:
    removeformat:
    resize_style:
    right:
    snippet:
    strike:
    styles:
    subscript:
    superscript:
    table:
    underline:
    undo:
    width:
  image:
    expandable: true
    height:
    image_size_attributes: true
    mime_type: image/png
    paths:
    resize_style:
    width:
  link:
    paths:
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
editor:
  default_path:
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Europe/Athens
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
